workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build iOS App
        script: |
          cd ios/App

          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build

    artifacts:
      - ios/App/build/**/*.app
      - ios/App/build/**/*